owner: worm-portal
repo: worm-status

sites:
  - name: WORM Portal
    url: https://worm-portal.asu.edu
    icon: https://worm-portal.asu.edu/favicon.ico
  - name: WORM JupyterHub
    url: https://worm-portal.asu.edu/jupyter
    expectedStatusCodes:
      - 200
      - 302  # JupyterHub might redirect to login

status-website:
  name: WORM Portal Status
  baseUrl: /worm-status
  logoUrl: https://worm-portal.asu.edu/path-to-logo.png
  introTitle: "WORM Portal System Status"
  introMessage: Real-time status monitoring for the Water-Organic-Rock-Microbe Portal
  
assignees:
  - gmboyer
  - worm-portal

user-agent: worm-portal-monitor

workflowSchedule:
  uptime: "*/5 * * * *"  # Check every 5 minutes
